"""사용자 언어 출력 — ko/en 메시지 테이블 + 언어 해석 체인.

체인: `payload.lang` > env `HANDOFF_LANG` > OS locale(`ko*`/`Korean*` → ko) > `en`.
저장 포맷 정체성(frontmatter 키·섹션 헤딩 10개·파일명 규칙)은 언어 무관 불변이다 —
번역 대상은 기본값(placeholder)·report·resume_prompt·경고·인덱스 장식 텍스트뿐이다.

**언어중립 파싱 지원**: `BLOCKER_DEFAULTS`(ko+en 전부의 "블로커 없음" 계열 상수집합)를
공개해, detail._read_topic_summary 가 어떤 언어로 저장된 본문이든 기본값-플레이스홀더를
정확히 빈 값 처리하도록 한다.
"""

from __future__ import annotations

import locale
import os

__all__ = [
    "resolve_lang",
    "msg",
    "BLOCKER_DEFAULTS",
    "GROUP_HEADINGS",
]

_SUPPORTED = ("ko", "en")


def resolve_lang(payload_lang: str | None) -> str:
    """언어 체인: payload > env HANDOFF_LANG > OS locale > en.

    OS locale 매핑: `ko` 로 시작하거나(`ko_KR`, `ko-KR`) `Korean` 으로 시작하면
    (Windows `Korean_Korea.949` 형태) 'ko'. 그 외 전부 'en'. 알 수 없는
    값(payload/env 포함)은 무조건 'en' 으로 폴백한다 — 지원 언어 외 값을 그대로
    통과시키지 않는다.
    """
    for candidate in (payload_lang, os.environ.get("HANDOFF_LANG")):
        if candidate:
            normalized = candidate.strip().lower()
            if normalized in _SUPPORTED:
                return normalized
            # 지원 목록 밖이면 이 단계는 무시하고 체인의 다음 단계로 넘어간다
            # (완전 미인식 값이라도 즉시 en 으로 확정하지 않고 계속 체인을 탄다는
            # 뜻은 아니다 — payload/env 가 명시값을 줬는데 오탈자면 en 이 안전한
            # 기본값이므로 여기서 en 확정).
            return "en"

    loc = _detect_os_locale()
    if loc and (loc.lower().startswith("ko") or loc.startswith("Korean")):
        return "ko"
    return "en"


def _detect_os_locale() -> str | None:
    """OS locale 문자열을 얻는다. Windows 는 `Korean_Korea` 형태를 돌려준다."""
    try:
        lang, _ = locale.getlocale()
    except (ValueError, TypeError):
        lang = None
    if lang:
        return lang
    for var in ("LC_ALL", "LC_MESSAGES", "LANG"):
        value = os.environ.get(var)
        if value:
            return value
    return None


def msg(key: str, lang: str, **kwargs) -> str:
    """메시지 테이블에서 `key` 를 `lang` 으로 조회, 포맷 인자 적용."""
    table = _MESSAGES.get(lang) or _MESSAGES["en"]
    template = table.get(key) or _MESSAGES["en"].get(key, key)
    return template.format(**kwargs) if kwargs else template


# --- 본문 섹션 기본값(placeholder) ---
# 저장 시 lang 에 맞는 값 하나만 쓰이지만, 파싱측(detail._read_topic_summary) 은
# 어떤 언어로 저장된 본문이든 인식해야 하므로 두 언어 전부를 상수집합으로 노출한다.

BLOCKER_DEFAULTS = frozenset({
    "현재 블로커 없음.",
    "No blockers.",
})

GROUP_HEADINGS = {
    "ko": {
        "active": "## 진행 중",
        "waiting": "## 대기",
        "watching": "## 관망",
    },
    "en": {
        "active": "## In Progress",
        "waiting": "## Waiting",
        "watching": "## Watching",
    },
}

_MESSAGES: dict[str, dict[str, str]] = {
    "ko": {
        # detail.assemble_body 기본값
        "done_default": "이번 세션에서 확정 완료된 것 없음 - 진행 중 또는 검토 단계.",
        "open_default": "- [ ] (다음 행동 미정)",
        "failed_attempts_default": "특별히 막힌 시도 없음.",
        "not_tried_default": "특별히 미시도 후보 없음.",
        "blockers_default": "현재 블로커 없음.",
        "decisions_default": "특기할 결정 없음.",
        "exact_next_step_default": "(다음 세션이 수행할 단계 미정)",
        "verification_default": "- 미검증",
        "files_touched_empty": "이번 세션에서 기록할 변경 파일 없음.",
        "git_state_not_git": "- git 저장소 아님 — git 상태 없음.",
        "git_state_note": "저장 시점 스냅샷이다. resume 시 현재 git 상태와 비교해 어긋나면 보고한다.",
        "git_state_line": "- 브랜치: `{branch}` · 커밋: `{commit}` · 작업트리: {tree}",
        "git_state_dirty": "dirty (uncommitted {count}개)",
        "git_state_clean": "clean",
        # INDEX.md
        "index_title": "# Handoff INDEX",
        "index_no_summary": "(요약 없음)",
        "index_status_archive_suggested": "done (archive suggested)",
        "index_status_archived": "archived ({group})",
        # CURRENT.md
        "current_title": "# {name} — 진행상황 인덱스",
        "current_notice": (
            "> AUTO-GENERATED by /handoff (또는 $handoff) — 손으로 고치지 말 것. "
            "상세 정본은 각 토픽 `.handoff/<topic>/`."
        ),
        "current_recent_heading": "## 최근 변경",
        "current_recent_empty": "- (없음)",
        "current_next_prefix": "다음: ",
        "current_blocker_prefix": "⚠ 블로커: ",
        # resume_prompt
        "resume_intro1": "새 세션이다. 직전 세션의 작업을 이어간다.",
        "resume_project_line": "- 프로젝트: {project_name}  (저장 머신 경로: {root})",
        "resume_topic_line": "- 토픽: {topic}",
        "resume_summary_line": "- 직전 요약: {summary_line}",
        "resume_tail1": (
            '먼저 이 프로젝트에서 `/handoff resume {topic}` 를 실행해'
            '(또는 "핸드오프 {topic} 이어받아줘")'
        ),
        "resume_tail2": "최신 핸드오프를 로드하고, Done/Open/Decisions/Git State 와 git drift 를 확인한 뒤",
        "resume_tail3": '"Exact Next Step" 부터 이어서 진행해줘. 작업 로그·보고는 사용자의 언어로.',
        # save report
        "save_report_title": "✅ 핸드오프 저장: `{topic}` ({status})",
        "save_report_project": "   프로젝트: {project_name}",
        "save_report_detail": "   정본: {detail_path}",
        "save_report_next": "📋 다음 세션에서 이어가려면 아래를 복사해 붙여넣으세요:",
        "warnings_header": "⚠ 경고:",
        # conflict report
        "conflict_title": (
            "⚠ 동시 저장 충돌: `{topic}` — 신규 본문은 저장됨(정본 보존), "
            "포인터/인덱스 갱신 중단."
        ),
        "conflict_project": "   프로젝트: {project_name}",
        "conflict_new_body": "   신규 본문: {detail_path}",
        "conflict_existing_latest": "   기존 최신: {other}",
        "conflict_none": "(없음)",
        "conflict_tail": (
            "두 최신본 중 어느 체인을 최신으로 할지 확인이 필요하다. "
            "resume 프롬프트는 충돌 해소 후 제공."
        ),
        # 경고 문자열
        "warn_unknown_source": "미인식 source '{value}' → 'claude-code' 로 강등 (허용: {allowed}).",
        "warn_summary_missing": (
            "summary 미입력 — resume 프롬프트에 요약 없이 토픽명만 들어간다. "
            "이어가기 품질을 위해 한 줄 요약을 채워라."
        ),
        "warn_project_id_uncommitted": (
            ".project-id 가 미커밋(untracked/staged-only) — 커밋·sync 전에는 타 머신이 "
            "같은 프로젝트로 인식 못 해 rename 감지·집계가 깨질 수 있음."
        ),
        "warn_project_id_uncommitted_reindex": (
            ".project-id 가 미커밋(untracked/staged-only) — `/sync` 커밋 전에는 타 머신이 "
            "같은 프로젝트로 인식 못 함."
        ),
        "warn_concurrent_save": (
            "저장 도중 LATEST.md 가 다른 writer 에 의해 변경됨 — 신규 본문은 보존, "
            "포인터/인덱스 갱신 중단. 두 최신본 중 어느 체인을 최신으로 할지 확인 필요."
        ),
        "warn_global_write_failed": "글로벌 CURRENT.md 갱신 실패(상세 정본은 보존됨): {exc}",
        "warn_no_handoff_dir": "`.handoff/` 없음 — 백필할 정본이 없어 글로벌 인덱스 미생성.",
        "warn_no_active_topics": "active 토픽 0개 — 빈 글로벌 인덱스를 만들지 않음.",
        "warn_reindex_failed": "글로벌 reindex 실패(정본 불변): {exc}",
        "warn_no_handoff_for_topic": "토픽 '{topic}' 의 handoff 가 없음.",
        "warn_broken_handoff": "broken handoff — LATEST 가 가리키는 {target} 가 없음.",
        "warn_git_drift": "git 상태가 저장 시점과 다름 — 이어가기 전 어느 상태에서 이어갈지 확인 필요.",
        "warn_topic_not_active": "토픽 '{topic}' 가 active 에 없음.",
        "warn_archive_exists": "이미 archived/{topic} 존재 — 덮어쓰지 않음.",
        "orphan_no_pointer": "LATEST.md 포인터 없음 — 본문 {newest} 가 가리켜지지 않음 (orphan).",
        "orphan_stale_pointer": (
            "LATEST.md 는 {latest_target} 를 가리키지만 더 새 본문 {newest} 가 존재 "
            "(orphan — 포인터 갱신 제안)."
        ),
        "warn_unrecognized_status": "미인식 status '{value}' → active 로 취급 (신 taxonomy: active/waiting/watching/done).",
        "warn_conflict_marker": "글로벌 CURRENT.md 에 머지충돌 마커 — 갱신 skip. `/sync` 후 `/handoff` 재실행.",
        "warn_remote_ahead": (
            "글로벌 `{pid_global}` remote-tracking ref 가 로컬보다 앞섬 — 갱신 skip. "
            "`/sync` 후 `/handoff` 재실행."
        ),
        "warn_legacy_project_id": "기존 글로벌 CURRENT.md 에 project_id 헤더 없음(레거시) — 재생성으로 정규화.",
        "warn_divergent_project_id": (
            "divergent project_id — 로컬 '{project_id}' vs 글로벌 '{existing_id}'. "
            "자동선택 안 함. 글로벌 갱신 중단, 수동 확인 필요."
        ),
        "warn_rename_suggested": (
            "글로벌 폴더명 '{matched_name}' ≠ 현재 basename '{name}' 이지만 project_id 동일 "
            "→ 기존 폴더에 기록. rename 제안: '{matched_name}' → '{name}'."
        ),
        "warn_secret_redacted": (
            "잠재 secret 라인 {idx} 를 글로벌 CURRENT.md 에서 [REDACTED] 처리 "
            "(git 히스토리는 안 지워짐 — 이미 커밋된 secret 은 filter-repo 필요)."
        ),
        "warn_invalid_sections": (
            "sections 필드가 dict 가 아님 — 무시하고 전 섹션 기본값으로 저장."
        ),
        "warn_unknown_section_key": (
            "미인식 section 키 '{section_key}' — 매핑되는 표준 섹션이 없어 버림(내용 유실 방지를 위한 경고)."
        ),
        "warn_duplicate_section_key": (
            "section '{canonical}' 에 중복 키 충돌 — '{kept}' 값을 채택, 무시된 키: {ignored}."
        ),
        "warn_invalid_section_value": (
            "section '{canonical}'(원본 키 '{section_key}') 의 값이 문자열이 아님 "
            "— 무시하고 기본값 사용."
        ),
    },
    "en": {
        "done_default": "Nothing confirmed complete this session - in progress or under review.",
        "open_default": "- [ ] (next action not decided)",
        "failed_attempts_default": "No notably blocked attempts.",
        "not_tried_default": "No notable untried candidates.",
        "blockers_default": "No blockers.",
        "decisions_default": "No notable decisions.",
        "exact_next_step_default": "(next session's step not decided)",
        "verification_default": "- Unverified",
        "files_touched_empty": "No files changed to record this session.",
        "git_state_not_git": "- Not a git repository — no git state.",
        "git_state_note": (
            "This is a snapshot at save time. On resume, compare against current "
            "git state and report any drift."
        ),
        "git_state_line": "- Branch: `{branch}` · Commit: `{commit}` · Working tree: {tree}",
        "git_state_dirty": "dirty ({count} uncommitted)",
        "git_state_clean": "clean",
        "index_title": "# Handoff INDEX",
        "index_no_summary": "(no summary)",
        "index_status_archive_suggested": "done (archive suggested)",
        "index_status_archived": "archived ({group})",
        "current_title": "# {name} — Progress Index",
        "current_notice": (
            "> AUTO-GENERATED by /handoff (or $handoff) — do not edit by hand. "
            "The detail source of truth is each topic's `.handoff/<topic>/`."
        ),
        "current_recent_heading": "## Recent Changes",
        "current_recent_empty": "- (none)",
        "current_next_prefix": "Next: ",
        "current_blocker_prefix": "⚠ Blocker: ",
        "resume_intro1": "New session. Continuing the previous session's work.",
        "resume_project_line": "- Project: {project_name}  (saved-machine path: {root})",
        "resume_topic_line": "- Topic: {topic}",
        "resume_summary_line": "- Previous summary: {summary_line}",
        "resume_tail1": (
            'First run `/handoff resume {topic}` in this project '
            '(or say "resume handoff {topic}")'
        ),
        "resume_tail2": "to load the latest handoff and check Done/Open/Decisions/Git State and git drift, then",
        "resume_tail3": 'continue from "Exact Next Step". Write work logs/reports in the user\'s language.',
        "save_report_title": "✅ Handoff saved: `{topic}` ({status})",
        "save_report_project": "   Project: {project_name}",
        "save_report_detail": "   Source of truth: {detail_path}",
        "save_report_next": "📋 To continue in the next session, copy and paste the block below:",
        "warnings_header": "⚠ Warnings:",
        "conflict_title": (
            "⚠ Concurrent save conflict: `{topic}` — new body was saved (source of truth "
            "preserved), pointer/index update aborted."
        ),
        "conflict_project": "   Project: {project_name}",
        "conflict_new_body": "   New body: {detail_path}",
        "conflict_existing_latest": "   Existing latest: {other}",
        "conflict_none": "(none)",
        "conflict_tail": (
            "Need to confirm which chain of the two latest versions should be treated "
            "as current. The resume prompt will be provided after the conflict is resolved."
        ),
        "warn_unknown_source": "Unrecognized source '{value}' → downgraded to 'claude-code' (allowed: {allowed}).",
        "warn_summary_missing": (
            "summary not provided — the resume prompt will contain only the topic name, "
            "no summary. Fill in a one-line summary for continuity quality."
        ),
        "warn_project_id_uncommitted": (
            ".project-id is uncommitted (untracked/staged-only) — until committed and "
            "synced, other machines can't recognize this as the same project, which can "
            "break rename detection and aggregation."
        ),
        "warn_project_id_uncommitted_reindex": (
            ".project-id is uncommitted (untracked/staged-only) — until `/sync` commits it, "
            "other machines can't recognize this as the same project."
        ),
        "warn_concurrent_save": (
            "LATEST.md was changed by another writer while saving — the new body was "
            "preserved, but the pointer/index update was aborted. Need to confirm which "
            "chain of the two latest versions should be treated as current."
        ),
        "warn_global_write_failed": "Global CURRENT.md update failed (detail source of truth preserved): {exc}",
        "warn_no_handoff_dir": "No `.handoff/` — nothing to backfill, global index not created.",
        "warn_no_active_topics": "0 active topics — not creating an empty global index.",
        "warn_reindex_failed": "Global reindex failed (source of truth unchanged): {exc}",
        "warn_no_handoff_for_topic": "No handoff exists for topic '{topic}'.",
        "warn_broken_handoff": "broken handoff — LATEST points to {target}, which does not exist.",
        "warn_git_drift": "git state differs from save time — confirm which state to continue from before proceeding.",
        "warn_topic_not_active": "Topic '{topic}' is not in active.",
        "warn_archive_exists": "archived/{topic} already exists — not overwriting.",
        "orphan_no_pointer": "No LATEST.md pointer — body {newest} is not referenced (orphan).",
        "orphan_stale_pointer": (
            "LATEST.md points to {latest_target} but a newer body {newest} exists "
            "(orphan — pointer update suggested)."
        ),
        "warn_unrecognized_status": "Unrecognized status '{value}' → treated as active (new taxonomy: active/waiting/watching/done).",
        "warn_conflict_marker": "Global CURRENT.md has merge conflict markers — update skipped. Re-run `/handoff` after `/sync`.",
        "warn_remote_ahead": (
            "Global `{pid_global}` remote-tracking ref is ahead of local — update skipped. "
            "Re-run `/handoff` after `/sync`."
        ),
        "warn_legacy_project_id": "Existing global CURRENT.md has no project_id header (legacy) — normalizing via regeneration.",
        "warn_divergent_project_id": (
            "Divergent project_id — local '{project_id}' vs global '{existing_id}'. "
            "Not auto-selecting. Global update aborted, manual confirmation needed."
        ),
        "warn_rename_suggested": (
            "Global folder name '{matched_name}' != current basename '{name}' but "
            "project_id matches → recording to the existing folder. Rename suggested: "
            "'{matched_name}' → '{name}'."
        ),
        "warn_secret_redacted": (
            "Redacted a potential secret on line {idx} of global CURRENT.md "
            "([REDACTED] — git history is not rewritten; secrets already committed need filter-repo)."
        ),
        "warn_invalid_sections": (
            "sections field is not a dict — ignored, all sections saved with defaults."
        ),
        "warn_unknown_section_key": (
            "Unrecognized section key '{section_key}' — no matching standard section, dropped "
            "(warned to prevent silent content loss)."
        ),
        "warn_duplicate_section_key": (
            "Duplicate key conflict for section '{canonical}' — kept '{kept}', ignored: {ignored}."
        ),
        "warn_invalid_section_value": (
            "Value for section '{canonical}' (raw key '{section_key}') is not a string "
            "— ignored, default used."
        ),
    },
}
